matrix:
  platform:
    - os: macos-13
      name: macos-x86_64
    - os: macos-latest
      name: macos-aarch64
    - os: ubuntu-22.04
      name: ubuntu-22.04
    - os: windows-2022
      name: windows-2022
  java:
    - 11
  sample:
    - DemoAppMain
    - DemoAppCachedInfo
